# -*- coding: utf-8 -*-
"""Whisper AI (speech to text).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttfVqt6g5wV7PW3gKTt8h5AfqdxPhM8P

**Documentation of open.ai - https://github.com/openai/whisper**

# Check Google Colab runtime on GPU for quicker processing.
"""

!nvidia-smi

"""# Step - 0 Install Requiredments
1. Install Whisper AI
2. Install FFmpeg is a free and open-source software project consisting of a suite of libraries and programs for handling video, audio, and other multimedia files and streams
"""

!pip install git+https://github.com/openai/whisper.git -q
!sudo apt update && sudo apt install ffmpeg

"""# Step - 1 Import Whisper for future use, and get_writer for transcription"""

import whisper
from whisper.utils import get_writer

"""# Step - 2 Load Whisper Model
There are five model sizes, four with English-only versions, offering speed and accuracy tradeoffs. Below are the names of the available models and their approximate memory requirements and inference speed relative to the large model; actual speed may vary depending on many factors including the available hardware.

"""

model = whisper.load_model("medium") #tiny, small, base, medium, large

"""# Step - 3 Give Input -- Upload the audio"""

from google.colab import files
uploaded = files.upload()

audio = "The problem with the internet that no one is talking about.mp3"

from IPython.display import Audio, display

display(Audio('The problem with the internet that no one is talking about.mp3', autoplay=True))

"""# Step - 4 Speech to Plain Text (Output)"""

result = model.transcribe(audio)
output_directory = "./"

# Save as a TXT file with hard line breaks
txt_writer = get_writer("txt", output_directory)
txt_writer(result, audio)

"""# Speech to Text Transcription (Output)

---


"""

# Save as an SRT file
srt_writer = get_writer("srt", output_directory)
srt_writer(result, audio)

"""# How to Calculating Word Error Rate (WER) and Character Error Rate (CER)"""

from editdistance import distance

reference = "This is a sample sentence."
hypothesis = "This is a sample sentence."

wer = distance(reference.split(), hypothesis.split()) / len(reference.split())
cer = distance(reference, hypothesis) / len(reference)

print("WER:", wer)
print("CER:", cer)